# -*- mode: ruby -*-
# vi: set ft=ruby :

ANSIBLE_GROUPS = {
  master: %w(node1),
  nodes: %w(node2 node3 node4),
  "all_groups:children": ["master", "nodes"]
}


# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "centos/7"

  (1..4).each do |n|
    name = "node#{n}"
    config.vm.define name do |node|
      node.vm.network :private_network, ip: "192.168.33.1#{n-1}"
      node.vm.hostname = name
      node.vm.provision "ansible" do |ansible|
        ansible.playbook = "playbook.yml"
        ansible.groups = ANSIBLE_GROUPS
      end
    end
  end

  config.vm.provider :libvirt do |libvirt|
    libvirt.cpus = 2
    libvirt.memory = 2000
  end

end
